/*
 * adapted by Nicolas Kniebihli INP-T ENSEEIHT
*/

#ifndef CONF_ASSER_H
#define CONF_ASSER_H

#ifdef __cplusplus
extern "C" {
#endif

#define MAX_PPRZ 9600

#define COMMANDS_NB 4
#define COMMAND_PITCH 0
#define COMMAND_ROLL 1
#define COMMAND_YAW 2
#define COMMAND_THRUST 3

#define STABILIZATION_RATE_GAIN_P 400
#define STABILIZATION_RATE_GAIN_Q 400
#define STABILIZATION_RATE_GAIN_R 350

#define GUIDANCE_V_MIN_ERR_Z POS_BFP_OF_REAL(-10.)
#define GUIDANCE_V_MAX_ERR_Z POS_BFP_OF_REAL( 10.)
#define GUIDANCE_V_MIN_ERR_ZD SPEED_BFP_OF_REAL(-10.)
#define GUIDANCE_V_MAX_ERR_ZD SPEED_BFP_OF_REAL( 10.)
#define GUIDANCE_V_MAX_SUM_ERR 2000000
#define GUIDANCE_V_HOVER_KP 283
#define GUIDANCE_V_HOVER_KD 18
#define GUIDANCE_V_HOVER_KI 13

#define STABILIZATION_ATTITUDE_REF_OMEGA_P 13.962634
#define STABILIZATION_ATTITUDE_REF_OMEGA_Q 13.962634
#define STABILIZATION_ATTITUDE_REF_OMEGA_R 8.72664625
#define STABILIZATION_ATTITUDE_REF_ZETA_R 0.85
#define STABILIZATION_ATTITUDE_REF_ZETA_P 0.85
#define STABILIZATION_ATTITUDE_REF_ZETA_Q 0.85
#define STABILIZATION_ATTITUDE_PHI_PGAIN 592
#define STABILIZATION_ATTITUDE_PHI_DGAIN 303
#define STABILIZATION_ATTITUDE_PHI_IGAIN 0
#define STABILIZATION_ATTITUDE_THETA_PGAIN 606
#define STABILIZATION_ATTITUDE_THETA_DGAIN 303
#define STABILIZATION_ATTITUDE_THETA_IGAIN 0
#define STABILIZATION_ATTITUDE_PSI_PGAIN 529
#define STABILIZATION_ATTITUDE_PSI_DGAIN 353
#define STABILIZATION_ATTITUDE_PSI_IGAIN 0
#define STABILIZATION_ATTITUDE_PHI_DDGAIN 0
#define STABILIZATION_ATTITUDE_THETA_DDGAIN 0
#define STABILIZATION_ATTITUDE_PSI_DDGAIN 52

#ifdef __cplusplus
}
#endif

#endif
