/*
 * Rassemble l'ensemble des paramètres de configurations du bloc moteur
 * adapted by Nicolas Kniebihli INP-T ENSEEIHT
 */

#define ACTUATORS_NB 4
#define COMMAND_PITCH 0
#define COMMAND_ROLL 1
#define COMMAND_YAW 2
#define COMMAND_THRUST 3
#define MAX_PPRZ 9600


#define SERVO_TOP_RIGHT_IDX 0
#define SERVO_TOP_LEFT_IDX 1
#define SERVO_BOTTOM_RIGHT_IDX 2
#define SERVO_BOTTOM_LEFT_IDX 3

#define MOTOR_MIXING_TRIM_ROLL 0
#define MOTOR_MIXING_TRIM_PITCH 0
#define MOTOR_MIXING_TRIM_YAW 0
#define MOTOR_MIXING_NB_MOTOR 4
#define MOTOR_MIXING_SCALE 255
#define MOTOR_MIXING_ROLL_COEF { 256, -256,  -256,  256 }
#define MOTOR_MIXING_PITCH_COEF {  256, 256, -256,  -256 }
#define MOTOR_MIXING_YAW_COEF { -256,  256, -256,  256 }
#define MOTOR_MIXING_THRUST_COEF {  256,  256,  256,  256 }

#define SERVO_TOP_LEFT 0
#define SERVO_TOP_LEFT_NEUTRAL 1
#define SERVO_TOP_LEFT_TRAVEL_UP_NUM 499
#define SERVO_TOP_LEFT_TRAVEL_UP_DEN 9600
#define SERVO_TOP_LEFT_TRAVEL_DOWN_NUM 1
#define SERVO_TOP_LEFT_TRAVEL_DOWN_DEN 9600
#define SERVO_TOP_LEFT_MAX 500
#define SERVO_TOP_LEFT_MIN 0

#define SERVO_TOP_RIGHT 1
#define SERVO_TOP_RIGHT_NEUTRAL 1
#define SERVO_TOP_RIGHT_TRAVEL_UP_NUM 499
#define SERVO_TOP_RIGHT_TRAVEL_UP_DEN 9600
#define SERVO_TOP_RIGHT_TRAVEL_DOWN_NUM 1
#define SERVO_TOP_RIGHT_TRAVEL_DOWN_DEN 9600
#define SERVO_TOP_RIGHT_MAX 500
#define SERVO_TOP_RIGHT_MIN 0

#define SERVO_BOTTOM_RIGHT 2
#define SERVO_BOTTOM_RIGHT_NEUTRAL 1
#define SERVO_BOTTOM_RIGHT_TRAVEL_UP_NUM 499
#define SERVO_BOTTOM_RIGHT_TRAVEL_UP_DEN 9600
#define SERVO_BOTTOM_RIGHT_TRAVEL_DOWN_NUM 1
#define SERVO_BOTTOM_RIGHT_TRAVEL_DOWN_DEN 9600
#define SERVO_BOTTOM_RIGHT_MAX 500
#define SERVO_BOTTOM_RIGHT_MIN 0

#define SERVO_BOTTOM_LEFT 3
#define SERVO_BOTTOM_LEFT_NEUTRAL 1
#define SERVO_BOTTOM_LEFT_TRAVEL_UP_NUM 499
#define SERVO_BOTTOM_LEFT_TRAVEL_UP_DEN 9600
#define SERVO_BOTTOM_LEFT_TRAVEL_DOWN_NUM 1
#define SERVO_BOTTOM_LEFT_TRAVEL_DOWN_DEN 9600
#define SERVO_BOTTOM_LEFT_MAX 500
#define SERVO_BOTTOM_LEFT_MIN 0
